FROM leplusorg/latex
MAINTAINER Mehedi Shafi <mehedishafi@hotmail.com>

LABEL version="1.1.0"

#ENV DEBIAN_FRONTEND noninteractive

# Install all TeX and LaTeX dependences

WORKDIR /data
VOLUME ["/data"]